# Generated by Django 4.2.13 on 2024-05-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
